SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE
    TABLE_NAME LIKE '%Actuals%CC%Summary%'
    OR TABLE_NAME LIKE '%Actuals%SAP%Transformation%'
ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION;